### ISSUE TITLE
Error in recreation

### ISSUE THREAD

**Issue by JustinWoods1** [RandomVertebrate/raspi-looper#8]
Hello! Love the project. 

I am trying to recreate, and get to the latency.py step with no issues. Here, our output starts to differ at the very end.
After the last JackShmReadWritePtr::...
Expression 'parameters->channelCount <=maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line 2818
Traceback (most recent call last): 
  File "latency.py", line 83, in <module>
    stream_callback = test_callback
  File "/usr/lib/python3/dist-packages/pyaudio.py". line 750, in open 
    stream = Stream(self, *args, **kwargs)
  File "usr/lib/python3/dist-packages/pyaudio.py", line 441, in __init__ 
    self._stream = pa.open(**arguments)
OSError: [Errno -9998] Invalid number of channels

Did you ever run into this issue? Could definitely use some help.

Thanks!

**Comment by RandomVertebrate** [comment]
As I recall, this happened to me when I didn't run the scripts as sudo. I
think it has something to do with overriding default soundcard selection,
though it is likely that I am mistaken.

**Comment by JustinWoods1** [comment]
Still running into this error even after running as sudo; any other ideas/recomendations?

**Comment by RandomVertebrate** [comment]
Hm, couldn't say.

Could you post your output from devices.py and setup.py? That might provide
some insight.

**Comment by RandomVertebrate** [comment]
Hey, so I recently found out that on newer RPi OS versions you have to uninstall pulseaudio to access ALSA. This is probably the problem. Try uninstalling pulse.
Sorry for the year-late response :P
